### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [dbsdk1/C202309#2]
### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/studentGrade
    - Warning: incompatible pointer to integer conversion initializing 'char' with an expression of type 'char[1]' [line 6]
         - char 자료형은 문자를 담는 자료형이기 때문에 '' (작은따옴표)를 사용해야 합니다. 변경해주세요

- WARNING in practice/week6/studentGrade
    - Warning: incompatible pointer to integer conversion initializing 'char' with an expression of type 'char[1]' [line 6]
         - char 자료형은 문자를 담는 자료형이기 때문에 '' (작은따옴표)를 사용해야 합니다. 변경해주세요

**Comment by dbsdk1** [comment]
"" 을 ' '으로 수정하였습니다.
